### ISSUE TITLE
Fix IW3 dumping of referenced assets

### ISSUE THREAD

**Issue by Laupetin** [ZoneTool/zonetool#21]
Dumping of referenced assets does not work currently. The linker will be stuck in an infinite loop when calling DB_FindXAssetHeader.

#20 temporarly fixes it with removing the code that tries to dumping referenced assets. This should maybe be fixed and reimplemented.

**Comment by RektInator** [comment]
Dumping referenced assets can be fixed by using DB_EnumXAssetsInternal instead. This function does not wait for the database thread to be ready.

**Comment by RektInator** [comment]
Dumping referenced assets should eventually be done for every linker, so that you do not have to pre-dump specific fastfiles like common_mp and code_post_gfx_mp for additional assets (techsets for example)
