### ISSUE TITLE
not properly dumped loaded sound in IW4 and IW5 

### ISSUE THREAD

**Issue by maxneed** [ZoneTool/zonetool#27]
the wav files are messed up in all dumped version ...in the earlier versions they are properly extracted besides that when I dump a map from IW5 and use the command buildzone in IW4 to generate fastfiles the tool always popup an error that some techsets are missing or crash when doesn't find some loaded sound files same thing happen for converting maps from IW4 to IW5...I never succeeded in converting maps between Iw4 and IW5 always there is some errors

**Comment by RektInator** [comment]
what version of zonetool does zonetool report?

**Comment by maxneed** [comment]
it report 0.0.0 but I compiled the new source code today

**Comment by RektInator** [comment]
I tested it and I indeed have the same issue. I resolved part of the issue now and it will be committed to the repository soon. 

Next to that, please do the following:
- if you are porting to IW4, export common_mp and code_post_gfx_mp (FROM IW4) and copy the techsets folders to the zonetool folder.
- do the same for IW5, but this time export the iw5 common_mp and code_post_gfx_mp fastfiles and copy the techsets to your IW5 zonetool (for porting to IW5).

**Comment by RektInator** [comment]
As for the loaded_sound issue, just confirmed it and it is indeed broken.

**Comment by maxneed** [comment]
I've done all what you suggested about common_mp and code_post_gfx_mp but there is always something missing...I noticed that the zonetool doesn't find techset if this line an example "techset,,mc_l_sm_r0c0s0_sat"  in CSV file contain two successive comma by eliminating the second comma in all lines the zonetool successfully find all the techsets but there is another problem some techsets refrence another techsets not existing in the csv file or in the techsets folder I cheked that...to continue the test I deleted all the non existing techsets but the tool crash when parsing fx staff in the csv file so I decided to delete those lines Finally The zonetool show successfully compiled fastfile "mp_dome"! but there is no fastfile generated I searched in the zone folder in usermaps no mp_dome.ff

**Comment by RektInator** [comment]
Hello,

You don't need to include techsets into your CSV file. I use the following CSV file for porting maps:
```
// tell zonetool we're building a map
map,

// reference map assets
col_map_mp,maps/mp/mp_dome.d3dbsp
gfx_map,maps/mp/mp_dome.d3dbsp
game_map_mp,maps/mp/mp_dome.d3dbsp
com_map,maps/mp/mp_dome.d3dbsp
fx_map,maps/mp/mp_dome.d3dbsp

// footstep sounds, reference means it will add , in front of the name (therefore reference it from another zone)
reference,true
loaded_sound,footsteps/foot_dirt01.wav
loaded_sound,footsteps/foot_dirt02.wav
loaded_sound,footsteps/foot_dirt03.wav
loaded_sound,footsteps/foot_dirt04.wav
loaded_sound,footsteps/foot_metal01.wav
loaded_sound,footsteps/foot_metal02.wav
loaded_sound,footsteps/foot_metal03.wav
loaded_sound,footsteps/foot_metal04.wav
loaded_sound,footsteps/mrk_foot_dirtsand01.wav
loaded_sound,footsteps/mrk_foot_dirtsand02.wav
loaded_sound,footsteps/mrk_foot_dirtsand03.wav
loaded_sound,footsteps/mrk_foot_dirtsand04.wav
loaded_sound,footsteps/foot_snow01.wav
loaded_sound,footsteps/foot_snow02.wav
loaded_sound,footsteps/foot_snow03.wav
loaded_sound,footsteps/foot_snow04.wav
reference,false

// add all xmodels
iterate,true
```

**Comment by RektInator** [comment]
Regarding the loaded sounds, see issue #28

**Comment by RektInator** [comment]
I will close this issue for now. If you need help, feel free to DM me on discord. You can either join the discord server mentioned in the README or add me as friend. My discord username is: RektInator 💻#7685

Thank you for your contribution.
