### ISSUE TITLE
Techsets exported from IW5 seem to be broken

### ISSUE THREAD

**Issue by RektInator** [ZoneTool/zonetool#30]
Techsets exported from IW5 seem to be broken. When porting an IW5 weapon to IW4, the weapon turns white.

**Comment by RektInator** [comment]
Seems only broken with mc_ techsets, wc_ techsets seem to be fine. Related to techset remapping?

**Comment by PrototypeTV** [comment]
I ported an IW5 map to IW4 and it also seems like m_ techsets have the same issue as mc_ techsets.

**Comment by RektInator** [comment]
Yes, this has been resolved in a closed-source variant of ZoneTool, this repo will probably be updated soon.
