### ISSUE TITLE
[BUG]VertexDecl ppcc0t0t0 not found

### ISSUE THREAD

**Issue by ghostr92** [ZoneTool/zonetool#39]
When i try to build zone to IW4 it gives me error VertexDecl ppcc0t0t0 not found what might be the issue ?

**Comment by RektInator** [comment]
That is because you need to dump the techsets from the game you are porting from. The base techsets can be found in common_mp / code_post_gfx_mp. Merge the techsets folders from these 2 dumps into zonetool/techsets
