### ISSUE TITLE
[BUG] dumpzone problems

### ISSUE THREAD

**Issue by Combine900** [ZoneTool/zonetool#41]
You cant dumpzone following fastfiles from mw2 for PC not even after a restart of zonetool.

"contingency.ff", "ending.ff", "estate.ff"
"Could not allocate asset - increase XASSET_ENTRY_POOL_SIZE"

**Comment by RektInator** [comment]
Yes, this is because too many assets are loaded at once. Not sure if this will be fixed because https://github.com/ZoneTool/zonetool-transpiler will most likely take over.

**Comment by Combine900** [comment]
> 
> 
> Yes, this is because too many assets are loaded at once. Not sure if this will be fixed because https://github.com/ZoneTool/zonetool-transpiler will most likely take over.

Alright, will there be a working release of this "new" tool or does it stay in source-code only?

**Comment by RektInator** [comment]
> > Yes, this is because too many assets are loaded at once. Not sure if this will be fixed because https://github.com/ZoneTool/zonetool-transpiler will most likely take over.
> 
> Alright, will there be a working release of this "new" tool or does it stay in source-code only?

For now you will have to compile it
