### ISSUE TITLE
[BUG] mw3 common.ff

### ISSUE THREAD

**Issue by Combine900** [ZoneTool/zonetool#42]
If you try too dumpzone the "common.ff" PC file of mw3 you will get a strange error message that you have not enough free space on your computer.

Is is possible too dump it somehow?

**Comment by RektInator** [comment]
This is not a bug, simply means too many assets have been loaded already. You can load it if you patch the game not to load stock zones. But I can tell you that common.ff contains nothing of interest.

**Comment by VladWinner** [comment]
> But I can tell you that common.ff contains nothing of interest.

@RektInator Do you know how to extract localization strings for MW3 SP?
