### ISSUE TITLE
[FEATURE] There could be a executable so this tool can actually be used

### ISSUE THREAD

**Issue by SpicyCupcakes** [ZoneTool/zonetool#49]
It is impossible to use this tool.  I tried searching about the pdb file, but there is no information on what this is and how to even use it.  I was really thinking I finally found a tool to decompile zone files from iw5 but this tool doesn't have a way to be used.

**Comment by RektInator** [comment]
https://github.com/ZoneTool/zonetool-binaries

**Comment by RektInator** [comment]
tool can definitely be used, just requires some effort from the end-users side.
