### ISSUE TITLE
[BUG] zonetool crashes

### ISSUE THREAD

**Issue by Combine900** [ZoneTool/zonetool#50]
Zonetool crashes on many .ff files for some reason if you try too dump them. [IW5, sp files]

crash dump(s)
https://www.mediafire.com/file/efln5ibagfa2xbb/crashdumps.rar/file

**Comment by RektInator** [comment]
What fastfiles did you dump? With what version of ZoneTool?

**Comment by Combine900** [comment]
> 
> 
> What fastfiles did you dump? With what version of ZoneTool?

get the crashdumps.rar in there are folders with the names of the used fastfiles, used "ver 1.0.205"

**Comment by Combine900** [comment]
Well.. does this tools get any updates..?

**Comment by RektInator** [comment]
No, this version of zonetool hasn't been supported in over a year.

**Comment by Combine900** [comment]
Is there a way too get access too the private build?
Or is there any new upcoming version?

Its really important for modders :/

**Comment by RektInator** [comment]
Not yet.

**Comment by Combine900** [comment]
Thank yow for the answers.
