### ISSUE TITLE
[BUG] how do I use this then if it is just a useless file.

### ISSUE THREAD

**Issue by SpicyCupcakes** [ZoneTool/zonetool#53]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information:**
 - OS: [e.g. Windows 7]
 - Version: [e.g. 1.0.118]
 - Linker: [e.g. IW4]

**Crash dump**
Link referring to the crashdump here (if there is a crashdump)

**Additional context**

**Comment by RektInator** [comment]
Download the DLL?
