### ISSUE TITLE
[BUG] dumpzone crashes on some iw4x files

### ISSUE THREAD

**Issue by CertainlyAria** [ZoneTool/zonetool#54]
Zonetool crashes and exits on some iw4x files without dumping anything.

Tested with latest zonetool binaries from [zonetool-binaries](https://github.com/ZoneTool/zonetool-binaries) and latest [zonetool dll](https://github.com/ZoneTool/zonetool/releases/tag/1.0.205).

`mp_crash_tropical`
![image](https://user-images.githubusercontent.com/44586130/107782675-963f0d00-6d5e-11eb-9aab-659268e26fdd.png)

`mp_cargoship`
![image](https://user-images.githubusercontent.com/44586130/107782828-c5557e80-6d5e-11eb-9966-3533635e26dc.png)

**Comment by RektInator** [comment]
IW4x zones are not supported.
