### ISSUE TITLE
out of memory (low of hard disk space)

### ISSUE THREAD

**Issue by SpunKy7769** [ZoneTool/zonetool#56]
when i try to dump a fastfile i get the "error out of memory you are probably low of hard disk space" i am not low on space i tried reinstalling the zonetoo.dll didnt fix it i tried changing to a different hdd with alot more space and that didnt fix it so i dont know what else to do.

**Comment by SpunKy7769** [comment]
im using v1.0.205 and trying to dump common.ff in mw3

**Comment by Dss0** [comment]
see https://github.com/ZoneTool/zonetool/issues/42
