### ISSUE TITLE
Is it possible to port CODOL xmodels with this tool?

### ISSUE THREAD

**Issue by vrpixel** [ZoneTool/zonetool#57]
I have a dump of CODOL files, and I would like to extract xmodels from them. Can this tool help me out in this?

**Comment by RektInator** [comment]
if you port them over to CoD4, ZoneTool can port them from CoD4 to MW2 and MW3.

**Comment by vrpixel** [comment]
But is that doable with codol files?
Even the iwi textures have different header. Is there are tutorial how to get the models into any usable format?

**Comment by RektInator** [comment]
No? ZoneTool only works with ZoneTool. You dump from one game and import in the other. ZoneTool does not support dumped assets from other tools. Import your assets using cod4 modtools, then you can bring them over to another game.
