### ISSUE TITLE
structureddata in IW4

### ISSUE THREAD

**Issue by ghostr92** [ZoneTool/zonetool#60]
hello,
        I dont know how to manipulate playerdatadef i want to enter new weapon entry but dont know how to using zonetool please suggest me. thanks

**Comment by RektInator** [comment]
In order to add custom weapons to structureddatadef, you must modify the asset structure before the asset is written (the write function writes the asset to disk). Please note that this wont work in combination with IW4x, because IW4x itself also does statfile modifications.

**Comment by ghostr92** [comment]
there isnt way to work with iw4x there might be if i can edit anything in iw4x source code.
