### ISSUE TITLE
[BUG] custom sound compiling issue

### ISSUE THREAD

**Issue by upl1nk-v01d** [ZoneTool/zonetool#62]
IW4 (v1.0.205 WIN7) zonetool doesn't compile correctly my custom sound.
Zonetool terminal outputs following log: 
 Parsing loaded_sound "v01d/misc/hello1.wav"...
 Sound null.wav not found, it will probably sound like a motorboat ingame!
![term](https://user-images.githubusercontent.com/56597891/129347292-4911cc99-22dc-4416-a883-f09f45ca8f15.png)

Result: in game with my script (gsc) invoking playLocalSound("hello") or playSound("hello") command my custom sound is not played.

Investigating created hello1.xss file content it seems that sound file pointing is incorrect (null.wav).
Please see picture at description end.

My v01d.csv source file in zone_source dir includes following content:
 **sndcurve,,$default
 loaded_sound,v01d/misc/hello1.wav
 sound, hello1**

My prepared zone dir and file structure:
|[iw4x]\
|-zone_source\
|--v01d.csv
|-zonetool\
|--loaded_sound\
|---v01d\
|----misc\
|-----hello1.wav

My dumped mod file v01d.ff dir and file struct:
|[iw4x]
|-dump
|--v01d(modname)\
|---loaded_sound\
|----v01d\
|-----misc\
|------hello1.wav
|--sounds\
|---hello.xss
|--v01d.csv
		
my dumped mod file v01d.csv content:
 **loaded_sound,v01d/misc/hello1.wav
 sndcurve,$default
 loaded_sound,null.wav
 sound,hello1
 rawfile,v01d**

my dumped mod file hello1.xss content:
![hello1](https://user-images.githubusercontent.com/56597891/129345133-5e545fa4-5c91-4600-a3ee-129264899507.png)

**Comment by RektInator** [comment]
And the input hello1.xss file?

**Comment by upl1nk-v01d** [comment]
Sorry? Do I also have to define xss input file in zone_source dir?
There are no tutorials, at least I couldn't find any.

**Comment by RektInator** [comment]
If you are writing a sound, you need a .xss file. This file tells the game what sound it needs to use. If you do not have a xss file, you cannot make a sound.

ZoneTool is not meant to write custom assets directly. ZoneTool is designed so you can dump a fastfile from 1 game and convert it for another game. So if you want custom assets, you need to use the CoD4 mod tools to create a mod.ff and then port it over to another game.

**Comment by upl1nk-v01d** [comment]
thanks :)
